name: build-apk
on: [workflow_dispatch, push]

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      # PASO AÑADIDO: Instalar las librerías del sistema necesarias para compilar NumPy.
      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libopenblas-dev

      - name: Cache Buildozer dependencies
        uses: actions/cache@v4
        with:
          path: .buildozer_global
          key: buildozer-cache-${{ runner.os }}-${{ hashFiles('**/buildozer.spec') }}
          restore-keys: |
            buildozer-cache-${{ runner.os }}-

      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        env:
          BUILDOZER_ANDROID_NDK: 25b
        with:
          workdir: .
          buildozer_version: stable
          command: buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: ${{ steps.buildozer.outputs.filename }}
