name: build-apk
on: [workflow_dispatch, push]

# Evita colas: al hacer un nuevo commit cancela el build anterior
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      # PASO AÑADIDO: Guardar y restaurar la caché de Buildozer
      # Esto acelerará drásticamente las compilaciones futuras.
      - name: Cache Buildozer dependencies
        uses: actions/cache@v4
        with:
          path: .buildozer_global # Directorio a guardar en caché
          key: buildozer-cache-${{ runner.os }}-${{ hashFiles('**/buildozer.spec') }}
          restore-keys: |
            buildozer-cache-${{ runner.os }}-

      # PASO ELIMINADO: La limpieza ya no es necesaria con la caché.
      # - name: Clean caches
      #   run: rm -rf .buildozer .buildozer_global bin

      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        env:
          BUILDOZER_ANDROID_NDK: 25b
        with:
          workdir: .
          buildozer_version: stable
          command: buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: ${{ steps.buildozer.outputs.filename }}
