name: build-apk
on: [workflow_dispatch, push]

# Evita colas: al hacer un nuevo commit cancela el build anterior
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      # Limpieza total para evitar residuos de builds previos
      - name: Clean caches
        run: rm -rf .buildozer .buildozer_global bin

      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        env:
          BUILDOZER_ANDROID_NDK: 25b
        with:
          workdir: .
          buildozer_version: stable
          command: buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: ${{ steps.buildozer.outputs.filename }}
